# Generated by Django 3.1.7 on 2021-03-27 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0002_auto_20200428_1904'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='doctor_file',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='picture',
        ),
    ]
