# Generated by Django 3.1.7 on 2021-04-03 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0004_role'),
        ('creator', '0006_auto_20210331_0826'),
    ]

    operations = [
    ]
