# Generated by Django 3.1.7 on 2021-04-03 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0004_doctor_favourite'),
        ('creator', '0009_doctor_fav'),
    ]

    operations = [
    ]
