# Generated by Django 3.1.7 on 2021-04-03 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0010_merge_20210403_1603'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='fav',
        ),
    ]
