# Generated by Django 3.0.5 on 2020-04-28 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorexperience',
            name='end_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='doctorexperience',
            name='start_date',
            field=models.DateField(blank=True),
        ),
    ]
