# Generated by Django 2.2 on 2021-03-27 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0003_auto_20210327_0743'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
