# Generated by Django 3.1.7 on 2021-03-31 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0004_doctor_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='phone_number',
            field=models.PositiveIntegerField(max_length=50),
        ),
    ]
