# Generated by Django 3.1.7 on 2021-03-31 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0005_auto_20210331_0753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='phone_number',
            field=models.IntegerField(max_length=50),
        ),
    ]
