# Generated by Django 3.1.7 on 2021-04-03 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0007_merge_20210403_0550'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, verbose_name='First name')),
                ('second_name', models.CharField(max_length=30, verbose_name='Second name')),
                ('contact_details', models.CharField(max_length=30, verbose_name='Contact details')),
                ('postcode', models.CharField(max_length=3, verbose_name='PostCode')),
                ('patient_status', models.CharField(max_length=30, verbose_name='Patient status')),
            ],
        ),
        migrations.DeleteModel(
            name='Role',
        ),
        migrations.AlterField(
            model_name='doctor',
            name='phone_number',
            field=models.PositiveIntegerField(max_length=50),
        ),
    ]
