# Generated by Django 3.1.7 on 2021-04-03 13:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creator', '0008_auto_20210403_0550'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='fav',
            field=models.BooleanField(default=datetime.datetime.now),
        ),
    ]
