version: "3.3"
services:
                
  nginx:
        image: tabibyab/nginx:v1
        build:
            context: './app/nginx'
        ports:
            - "80:80"
        volumes:
            - ./app/python/codes:/var/www/html
            - ./app/nginx/conf.d/nginx-site.conf:/etc/nginx/conf.d/nginx-site.conf
        depends_on: 
         - app   
  app:
        image: tabibtab/python-app:v1
        build:
            context: './app/python'
        ports:
            - "8009:8009"
        volumes:
            - ./app/python/codes:/opt/app/tabibyab  

